### ISSUE TITLE
I used the northern hemisphere data, and I got a slice number y that was in the southern hemisphere, and it looked like something was wrong.

### ISSUE THREAD

**Issue by kuaiqushangzixiba** [tehamalab/gdal2tiles#6]
* gdal2tiles version:
* GDAL version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by kuaiqushangzixiba** [comment]
The northern and southern hemispheres were sliced in opposite directions.

**Comment by kuaiqushangzixiba** [comment]
why ,  sb can help me?

**Comment by machakux** [comment]
@kuaiqushangzixiba It could be an issue related to coordinate reference system of your data.

Have you tried specifiying the correct s_srs value? I mean something like `gdal2tiles.generate_tiles(input_file, output_folder, s_srs="<YOUR_SRS>")`.

What happens when you directly use the [gdal2tile.py](https://www.gdal.org/gdal2tiles.html) utility script available from the [GDAL project](https://github.com/OSGeo/gdal)?

**Comment by machakux** [comment]
Closing this issue because it seems inactive. Feel free to re open if the issue still exists.
